package com.lipy.jotter.dao.daocore;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table NOTE.
 */
public class Note implements Serializable{

    private Long id;
    private Integer note_id;
    private String guid;
    private Integer status;
    private String tag;
    private String label;
    private String content;
    private String imagePath;
    private String voicePath;
    private Long createTime;
    private Long lastOprTime;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, Integer note_id, String guid, Integer status, String tag, String label, String content, String imagePath, String voicePath, Long createTime, Long lastOprTime) {
        this.id = id;
        this.note_id = note_id;
        this.guid = guid;
        this.status = status;
        this.tag = tag;
        this.label = label;
        this.content = content;
        this.imagePath = imagePath;
        this.voicePath = voicePath;
        this.createTime = createTime;
        this.lastOprTime = lastOprTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNote_id() {
        return note_id;
    }

    public void setNote_id(Integer note_id) {
        this.note_id = note_id;
    }

    public String getGuid() {
        return guid;
    }

    public void setGuid(String guid) {
        this.guid = guid;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getTag() {
        return tag;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImagePath() {
        return imagePath;
    }

    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }

    public String getVoicePath() {
        return voicePath;
    }

    public void setVoicePath(String voicePath) {
        this.voicePath = voicePath;
    }

    public Long getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    public Long getLastOprTime() {
        return lastOprTime;
    }

    public void setLastOprTime(Long lastOprTime) {
        this.lastOprTime = lastOprTime;
    }

}
