package com.lipy.jotter.dao.daocore;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table USER.
 */
public class User implements Serializable {

    private Long id;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private String userpassword;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String userName, String userpassword) {
        this.id = id;
        this.userName = userName;
        this.userpassword = userpassword;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getUserpassword() {
        return userpassword;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserpassword(String userpassword) {
        this.userpassword = userpassword;
    }

}
